# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK4Voy-aP_kjaeJoNusfym6tDh09RRkH
"""

# Write a program that calculates the area of a triangle using the formula A = (b * h) / 2.

base = float(input('Enter first side: '))
height = float(input('Enter second side: '))

area = (base*height )/ 2


print("The area of the triangle is %0.2f" %area)