# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dI756sOppqx_VoNL2aGLGOMHTRX_7SZv
"""

# Write a program that prompts the user to enter two floating-point numbers and then calculate their average.

num1= float(input("Enter the first floating-point number"))

num2= float(input("Enter the second floating-point number"))

average=(num1+num2)/2

print("The average is %f" %average)